name: Deploy Frontend to Server

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

    - name: Build application
      run: pnpm run build
      env:
        NODE_ENV: production

    - name: Create deployment archive
      run: |
        tar -czf deployment.tar.gz \
          .next/ \
          public/ \
          package.json \
          pnpm-lock.yaml \
          next.config.mjs \
          ecosystem.config.js \
          deploy.sh \
          generate-nginx-config.sh

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # Create deployment directory
          mkdir -p /tmp/watch-party-deployment
          cd /tmp/watch-party-deployment

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        source: "deployment.tar.gz"
        target: "/tmp/watch-party-deployment/"

    - name: Execute deployment script
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /tmp/watch-party-deployment
          tar -xzf deployment.tar.gz
          chmod +x deploy.sh
          chmod +x generate-nginx-config.sh
          sudo ./deploy.sh watch-party.brahim-elhouss.me
